name: Assign

on:
  issue_comment:
    types:
      - created

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/assign' }}
    steps:
      - id: print
        run: gh issue view $ISSUE --json assignees
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}