name: Assign

on:
  issue_comment:
    types:
      - created

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == '/assign' }}
    steps:
      - name: 'Auto-assign issue'
        uses: Suvraneel/Issue_Watcher@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          author: "${{github.actor}}"
          repo: "bartick/toxic-cicd"
          maxIssue: 2